# Generated by Django 3.2 on 2022-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
