# Generated by Django 3.2 on 2022-04-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
        ('actions', '0007_auto_20220409_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
