# Generated by Django 3.2 on 2022-03-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_deliveryinfor'),
        ('orders', '0003_auto_20220317_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_infor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.deliveryinfor'),
            preserve_default=False,
        ),
    ]
